### ISSUE TITLE
The Program Is Trying To Delete The Cookie File Even When It Doesn't Exists That Stops it.

### ISSUE THREAD

**Issue by DEMON1A** [adnane-X-tebbaa/GRecon#1]
- You're Deleting The Cookie File On `.google-cookie` Without Validating If This File Exists Or Not. I Believe Google Is Leaving a Cookie But You're Deleting It Multi Times Even When It Doesn't Leave Cookies File Sometimes. That Stop The Hall Process Here And The User Have To Start The Recon Over Again.

- Simple Fix Here. Before Deleting The Cookie File Validate If It Exists Or Not Using `os.path.exists()`

```
if os.path.exists(".google-cookie"):
    os.remove(".google-cookie")
else:
    pass
```

**Comment by adnane-X-tebbaa** [comment]
Fixed!
