### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by hassankhan98** [adnane-X-tebbaa/GRecon#10]
any solution?
![Screen Shot 2021-04-10 at 12 06 23 PM](https://user-images.githubusercontent.com/33081303/114261720-8d348a00-99f5-11eb-817a-1b3fa8bcae3e.png)
![Screen Shot 2021-04-10 at 12 06 25 PM](https://user-images.githubusercontent.com/33081303/114261726-945b9800-99f5-11eb-8a7f-63ed2d91cf10.png)

**Comment by adnane-X-tebbaa** [comment]
can you provide what python version you Work with?
Python 3.8.X ?

**Comment by NovusEdge** [comment]
Here's a stackoverflow thread discussing this issue: https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error
