### ISSUE TITLE
it stopped / (.google-cookie) file / (partially solved/waiting for Reviews)

### ISSUE THREAD

**Issue by NaveenBen** [adnane-X-tebbaa/GRecon#3]
Traceback (most recent call last):
  File "/mnt/c/Users/r00t/Desktop/tool/GRecon/grecon.py", line 80, in <module>
    os.remove(".google-cookie")
FileNotFoundError: [Errno 2] No such file or directory: '.google-cookie'

**Comment by NaveenBen** [comment]
no file is created

**Comment by adnane-X-tebbaa** [comment]
More Details please!

**Comment by lordOfSadi** [comment]
> no file is created

Same problem..

**Comment by NaveenBen** [comment]
[>] Looking For Subdomains...
https://www.latest.facebook.com/luckykeranvn/
https://pt-br.ja-jp.m.lite.facebook.com/candidfocusTx/app/208195102528120/?ref=page_internal
http://tl-ph.v2.connect.facebook.com/help/instagram/search/546541825361643
https://www.business.cinyour.facebook.com/bbweightedblanket/

Traceback (most recent call last):
  File "/mnt/c/Users/r00t/Desktop/tool/GRecon/grecon.py", line 80, in <module>
    os.remove(".google-cookie")
FileNotFoundError: [Errno 2] No such file or directory: '.google-cookie'

**Comment by adnane-X-tebbaa** [comment]
Can you Check the Directory 
Do cd Grecon then grecon.py

**Comment by NaveenBen** [comment]
> Can you Check the Directory
> Do cd Grecon then grecon.py  
yeh

┌[r00t]-(/m/c/U/r00t)
└> cd Desktop/tool/GRecon/
┌[r00t]-(/m/c/U/r/D/t/GRecon)-[git://main …1]-
└> python3 grecon.py

Cheking Update...
Update Status...[NO UPDATE]
GRecon V1.0
Resuming...

Current Micro Plugins :

[>] Subdomains...[UP]
[>] Sub-Subdomains...[UP]
[>] Signup/Login pages...[UP]
[>] Dir Listing...[UP]
[>] Exposed Docs...[UP]
[>] WordPress Entries...[UP]
[>] Pasting Sites...[UP]

 __  __
/ _ |__)_ _ _  _
\__)| \(-(_(_)| ) V1.0
 GRecon by @TebbaaX (Adnane)

[+] Set Target (site.com) : *.*.google.com

[>] Looking For Subdomains...

Traceback (most recent call last):
  File "/mnt/c/Users/r00t/Desktop/tool/GRecon/grecon.py", line 80, in <module>
    os.remove(".google-cookie")
FileNotFoundError: [Errno 2] No such file or directory: '.google-cookie'
┌[r00t]-(/m/c/U/r/D/t/GRecon)-[git://main …1]-
└>

**Comment by adnane-X-tebbaa** [comment]
Hi @NaveenBen can you check now,let me know soon as you try

**Comment by lordOfSadi** [comment]
> Hi @NaveenBen can you check now,let me know soon as you try

Solved , Thanks

**Comment by NaveenBen** [comment]
solved
