### ISSUE TITLE
Pasting Plugin Suffer From The Same Issue With '.google-cookie'. P.S Exiting Before Deleting The Config.

### ISSUE THREAD

**Issue by DEMON1A** [adnane-X-tebbaa/GRecon#5]
- You did fix the issue with the main script `grecon.py` and you missed `plugins/pasting.py` it's still showing errors on some targets since it can't find the '.google-cookie' file to delete it. that doesn't affect the recon data since all of them will be printed. it's just the error message here. more likely 'Best Practice'. you can use the same fix here

```
if os.path.exists(".google-cookie"):
    os.remove(".google-cookie")
else:
    pass
```

- Also, you're exiting from the program using `exit()` on line *35* before deleting the config file `grecon.config` and showing the end message. just fix this issue just remove the exit function.

**Comment by adnane-X-tebbaa** [comment]
Fixed! Thank you
