### ISSUE TITLE
Hey, Help Required!

### ISSUE THREAD

**Issue by StealerCook** [adnane-X-tebbaa/GRecon#7]
How to skip few scan. For example if I want to get only the paste site reference of target domain so i don't want to raise 429 error during on other stuff. Do we have an option for that?

**Comment by DEMON1A** [comment]
I don't think there's an option for that but if you want to run the pasting plugin without the other scans you can do it by changing the directory inside the `plugins` folder then create a local file `grecon.config` with your target. for example you can use this `echo 'example.com' > grecon.config`. then run the pasting module using python. `python3 pasting.py`. that will grap the pastbin results for you without running the other scans. just make sure you're on the plugins folder while doing all of this.

**Comment by adnane-X-tebbaa** [comment]
you can use grecon cli  where you can use  your own dorks or search queries scan skipping is not available as option currently 
also if you faced Error 429 (just change your ip or use a vpn along with the tool)

**Comment by StealerCook** [comment]
Yes Thank you.
